### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by rizlik** [marc0l92/joplin-plugin-drawio#2]
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/marc0l92/joplin-plugin-drawio/issues/new#), which will temporarily disable all plugins.

Message
Cannot read properties of null (reading 'webContents')

Version info
Joplin for Desktop

Copyright © 2016-2022 Laurent Cozic
Joplin 2.7.13 (prod, linux)

Client ID: 1d8e8e32c71440a980935c73b5765ca6
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 5b5165d
Plugins
[
    {
        "id": "com.github.marc0l92.joplin-plugin-drawio",
        "name": "Draw.io",
        "enabled": true,
        "version": "0.1.0"
    }
]
Stack trace
TypeError: Cannot read properties of null (reading 'webContents')
    at /tmp/.mount_Joplin4LKnVV/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.js:768:40
    at commitHookEffectList (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19980:11)
    at commitPassiveHookEffects (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20015:11)
    at HTMLUnknownElement.callCallback (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at flushPassiveEffectsImpl (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22868:7)
    at unstable_runWithPriority (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643:12)
    at runWithPriority$2 (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305:10)
    at flushPassiveEffects (/tmp/.mount_Joplin4LKnVV/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22841:10)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by marc0l92** [comment]
Are you able to reproduce this issue?
What are the step that make Joplin crash?

**Comment by marc0l92** [comment]
No feedback received about this issue
